name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: Platane/snk@v3
        with:
          github_user_name: marylin-monroe
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=purple&color_dots=yellow,orange,red,magenta,blue
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&animation_speed=5
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#0d1117,#161b22,#21262d,#30363d,#484f58
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update snake animation" -a || exit 0
          git push
