name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: Platane/snk@v3
        with:
          github_user_name: marylin-monroe
          outputs: dist/github-contribution-grid-snake.svg
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update snake" -a || exit 0
          git push
